const IMAGES={
    logo: require('./my logo.png'),
    homeimg: require('./homeimg.jpg'),
    homeimg2:require('./IMG_7190-01~2.jpeg'),
    homeslider1: require('./project-1287781_1920.jpg'),
    homeslider2: require('./mini_project_angular_hide.png'),
    ej2017: require('./2017.jpg'),
    ej2018: require('./Capture.PNG'),
    ej2019: require('./2019.jpg'),
    ej2020: require('./psit.jpeg'),
    ej2021: require('./IMG_20210916_102043-01_2.jpeg'),
    ej2022: require('./IMG20220914143327.jpg'),
    ej2023: require('./IMG_20210126_203039_514.jpg'),
    p_escutcheon:require('./mini_project_angular_hide.png'),
    p_green:require('./canvas_green_screen.png'),
    p_todo:require('./canvas_todo_list.png'),
    html:require('./html.png'),
    css:require('./css3.png'),
    js:require('./js.png'),
    python:require('./python.png'),
    canvas:require('./html canvas.png'),
    cpp:require('./c-logo-png-transparent.png'),
    angular:require('./Angular_full_color_logo.svg.png'),
    bootstrap:require('./Bootstrap_logo.png'),
    tailwind:require('./Tailwind-img.png'),
    monogodb:require('./Mongodb.png'),
    nodejs:require('./nodejs.png'),
    react:require('./react.png'),
    git:require('./Git.png'),
    signature:require('./signature.png'),
    comingsoon:require('./coming-soon-1898936.jpg'),
    stackoverflow: require('./stackoverflow.png'),
    samvad: require('./image.png')
}
export default IMAGES;